### ISSUE TITLE
error uploading to ipfs with community api

### ISSUE THREAD

**Issue by badxwolfyz** [codeSTACKr/video-source-code-create-nft-collection#10]
i keep receiving this error once i run node utlis/nftport/uploadfiles.js

my api in community api

i think it keep uploading same file number everytime i run it

i used all new updated mint upload fix files and codes

> `error:FetchError: request to https://api.nftport.xyz/v0/files failed, reason: write ECONNABORTED
error:FetchError: request to https://api.nftport.xyz/v0/files failed, reason: write ECONNRESET
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
1037.png uploaded & 1037.json updated!
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
1006.png uploaded & 1006.json updated!
1034.png uploaded & 1034.json updated!
1004.png uploaded & 1004.json updated!
1003.png uploaded & 1003.json updated!
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
1005.png uploaded & 1005.json updated!
102.png uploaded & 102.json updated!
1007.png uploaded & 1007.json updated!
1033.png uploaded & 1033.json updated!
1002.png uploaded & 1002.json`

**Comment by comancosmin** [comment]
I have the same issue!

`PS C:\Users\Cosmin\Desktop\hashlips_art_engine-1.1.1_update> node utils/nftport/uploadFiles.js
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
1.png uploaded & 1.json updated!
16.png uploaded & 16.json updated!`

**Comment by ChristianErdtmann** [comment]
Me the same. But not only with the uploadefiles.js

When i execute uploadFiles.js i get the following code:

error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
10.png uploaded & 10.json updated!
2.png uploaded & 2.json updated!

This time it updated the 10 and 2 png + jason but still have a problem with the rest. Please help

Similar Problem with the uploadeMetas.js

Here i get 

undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
Crypto Aliens #1 metadata uploaded & added to _ipfsMetas.json
Crypto Aliens #10 metadata uploaded & added to _ipfsMetas.json

The #1 and secound should be defined right but the rest not.

And when i try to mint i get, think because of the top two errors the following error:

PS E:\NFTMinter1000Oversea\video-source-code-create-nft-collection> node utils/nftport/mint.js
E:\NFTMinter1000Oversea\video-source-code-create-nft-collection\utils\nftport\mint.js:31
    token_id: meta.custom_fields.edition,
                                 ^

TypeError: Cannot read properties of undefined (reading 'edition')
    at E:\NFTMinter1000Oversea\video-source-code-create-nft-collection\utils\nftport\mint.js:31:34
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\NFTMinter1000Oversea\video-source-code-create-nft-collection\utils\nftport\mint.js:23:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Need a Solution for this Problems please.

**Comment by econcepcion** [comment]
Did you figure this out?  

error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

Thanks

**Comment by codeSTACKr** [comment]
fixed with latest code:
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints

**Comment by mattstehling** [comment]
Im getting this error when trying to upload just five images to IPFS. 

error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1
